---
- name: Развернуть инфраструктуру wordpress
  hosts: wordpress_servers
  become: true

  vars:
    project_dir: /opt/wp-monitoring

  tasks:
    - name: Установка необходимых пакетов
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-v2
          - fail2ban
          - openssl
        state: present
        update_cache: true

    - name: Запуск Docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
      when: not ansible_check_mode

    - name: Запуск Fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: started
        enabled: true
      when: not ansible_check_mode

    - name: Установка конфигурации Fail2ban
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../fail2ban/jail.local"
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: "0644"
      notify: Перезапуск Fail2ban

  handlers:
    - name: Перезапуск Fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: restarted